spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campusedge
    username: ${DB_USER:root}
    password: ${DB_PASS}
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USER:}
    password: ${BREVO_PASS:}

jwt:
  secret: ${JWT_SECRET}
  expiry: 86400000

app:
  allowed-email-domain: pvgcoenashik.org
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

logging:
  level:
    org.springframework.security: DEBUG